'use strict';

const path = require('path');
const {
  app, BrowserWindow, ipcMain, Notification, Tray, Menu, shell, nativeImage,
} = require('electron');

const { Store, NEW_BADGE_MS } = require('./store.js');
const { Scanner } = require('./scanner.js');
const net = require('./net.js');
const oui = require('./oui.js');
const discover = require('./discover.js');
const ports = require('./ports.js');

let mainWindow = null;
let tray = null;
let store = null;
let scanner = null;
let scanTimer = null;
let lastScan = null;
let scanError = null;
let quitting = false;
let portScanning = null; // device id whose ports are being scanned right now
let pingSession = null;  // { id, cancelled } for the live ping graph

// Two minutes of samples is plenty to spot a flaky link, and bounds a session
// that the user walks away from.
const PING_SESSION_MAX = 120;

// app.quit() is asynchronous, so a losing second instance can still reach
// whenReady and open its own Store over the same devices.json. Everything that
// touches state is gated on holding the lock.
const gotLock = app.requestSingleInstanceLock();
if (!gotLock) app.quit();

function ouiUserPath() {
  return path.join(app.getPath('userData'), 'oui.json');
}

function buildState() {
  return {
    devices: store.list(),
    settings: store.getSettings(),
    interfaces: net.listInterfaces(),
    scanning: scanner.running,
    lastScan,
    scanError,
    oui: oui.stats(),
    newBadgeMs: NEW_BADGE_MS,
    portScanning,
    pinging: pingSession ? pingSession.id : null,
  };
}

function pushState() {
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send('state:changed', buildState());
  }
  updateTray();
}

function updateTray() {
  if (!tray) return;
  const devices = store.list();
  const online = devices.filter((d) => d.online).length;
  const unseen = devices.filter((d) => !d.acknowledged).length;
  tray.setToolTip(`JomNetScan - ${online} online${unseen ? `, ${unseen} unnamed` : ''}`);
  tray.setContextMenu(Menu.buildFromTemplate([
    { label: `${online} device${online === 1 ? '' : 's'} online`, enabled: false },
    { type: 'separator' },
    { label: 'Open JomNetScan', click: showWindow },
    { label: 'Scan now', enabled: !scanner.running, click: () => runScan('manual') },
    { type: 'separator' },
    { label: 'Quit', click: () => { quitting = true; app.quit(); } },
  ]));
}

function assetPath(name) {
  return path.join(__dirname, '..', 'assets', name);
}

/** Both are generated by `npm run make-icon`. */
function trayIcon() {
  return nativeImage.createFromPath(assetPath('tray.png'));
}

async function runScan(trigger) {
  if (scanner.running) return;
  scanError = null;
  pushState();
  try {
    const result = await scanner.scan(store.getSettings());
    const newDevices = store.merge(result.devices, result.startedAt);
    store.expireNewFlags();
    lastScan = {
      at: result.finishedAt,
      trigger,
      count: result.devices.length,
      newCount: newDevices.length,
    };

    if (newDevices.length && store.getSettings().notifyOnNew && Notification.isSupported()) {
      const names = newDevices
        .map((d) => d.hostname || d.vendor || d.ip)
        .slice(0, 3)
        .join(', ');
      new Notification({
        title: newDevices.length === 1 ? 'New device on your network' : `${newDevices.length} new devices`,
        body: `${names}${newDevices.length > 3 ? ', ...' : ''} - open JomNetScan to name it.`,
      }).on('click', showWindow).show();
    }
  } catch (err) {
    scanError = err.message;
  } finally {
    pushState();
  }
}

function rescheduleAutoScan() {
  if (scanTimer) clearInterval(scanTimer);
  scanTimer = null;
  const { autoScan, intervalMinutes } = store.getSettings();
  if (!autoScan) return;
  const ms = Math.max(1, Number(intervalMinutes) || 5) * 60 * 1000;
  scanTimer = setInterval(() => runScan('auto'), ms);
}

function showWindow() {
  if (!mainWindow || mainWindow.isDestroyed()) {
    createWindow();
    return;
  }
  if (mainWindow.isMinimized()) mainWindow.restore();
  mainWindow.show();
  mainWindow.focus();
}

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1120,
    height: 760,
    minWidth: 820,
    minHeight: 520,
    backgroundColor: '#12141a',
    title: 'JomNetScan',
    icon: assetPath('icon.png'),
    autoHideMenuBar: true,
    webPreferences: {
      preload: path.join(__dirname, '..', 'preload', 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
    },
  });

  mainWindow.loadFile(path.join(__dirname, '..', 'renderer', 'index.html'));

  // A hidden window can't show a graph; don't keep pinging into the void.
  mainWindow.on('close', () => { if (pingSession) { pingSession.cancelled = true; pingSession = null; } });

  mainWindow.on('close', (e) => {
    if (!quitting && store.getSettings().minimizeToTray) {
      e.preventDefault();
      mainWindow.hide();
    }
  });

  // Nothing in this app should open a second window or navigate away.
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    if (/^https?:\/\//.test(url)) shell.openExternal(url);
    return { action: 'deny' };
  });
}

function start() {
  store = new Store(app.getPath('userData'));
  scanner = new Scanner();
  oui.load([ouiUserPath(), path.join(__dirname, '..', '..', 'data', 'oui.json')]);

  // Earlier builds stored service identifiers as announced names, and a merge
  // keeps the last one it saw. Drop anything the current filter would reject.
  let dropped = 0;
  for (const device of store.list()) {
    if (device.discoveredName && discover.looksLikeIdentifier(device.discoveredName)) {
      device.discoveredName = null;
      dropped += 1;
    }
  }
  if (dropped) store.saveDevices();

  scanner.on('progress', (payload) => {
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.webContents.send('scan:progress', payload);
    }
  });

  createWindow();
  tray = new Tray(trayIcon());
  tray.on('double-click', showWindow);
  updateTray();

  // Badges age out on their own clock, not the scan clock - otherwise turning
  // auto-scan off would leave them on screen indefinitely.
  store.expireNewFlags();
  setInterval(() => { if (store.expireNewFlags()) pushState(); }, 60 * 1000);

  rescheduleAutoScan();
  runScan('startup');
}

if (gotLock) {
  app.on('second-instance', showWindow);
  app.whenReady().then(start);
}

app.on('before-quit', () => { quitting = true; });
app.on('window-all-closed', () => { /* tray keeps the app alive on Windows */ });

ipcMain.handle('state:get', () => buildState());

ipcMain.handle('scan:run', async () => {
  await runScan('manual');
  return buildState();
});

ipcMain.handle('device:rename', (_e, { id, name }) => {
  store.rename(id, name);
  pushState();
  return buildState();
});

ipcMain.handle('device:save', (_e, { id, name, notes }) => {
  store.update(id, { name, notes });
  pushState();
  return buildState();
});

ipcMain.handle('device:notes', (_e, { id, notes }) => {
  store.setNotes(id, notes);
  pushState();
  return buildState();
});

ipcMain.handle('device:acknowledge', (_e, { ids }) => {
  store.acknowledge(ids || []);
  pushState();
  return buildState();
});

ipcMain.handle('device:adoptAnnounced', (_e, { ids }) => {
  store.adoptAnnounced(ids || null);
  pushState();
  return buildState();
});

/**
 * Port scans only ever run against a device already in the list, addressed by
 * its stored id - there is no way to point this at an arbitrary host from the
 * UI. One at a time, on request, never as part of a sweep.
 */
ipcMain.handle('ports:scan', async (_e, { id }) => {
  const device = store.get(id);
  if (!device || portScanning) return buildState();
  portScanning = id;
  pushState();
  try {
    const open = await ports.scanPorts(device.ip, {
      onProgress: (done, total) => {
        if (mainWindow && !mainWindow.isDestroyed()) {
          mainWindow.webContents.send('ports:progress', { id, done, total });
        }
      },
    });
    store.setPorts(id, { scannedAt: new Date().toISOString(), open });
  } catch (err) {
    store.setPorts(id, { scannedAt: new Date().toISOString(), open: [], error: err.message });
  } finally {
    portScanning = null;
    pushState();
  }
  return buildState();
});

/**
 * A live ping session against one device: one ping a second, streamed to the
 * UI as it goes, until it is stopped or hits the cap. Only one runs at a time,
 * and like the port scan it is addressed by stored device id.
 */
ipcMain.handle('ping:start', async (_e, { id }) => {
  const device = store.get(id);
  if (!device) return buildState();
  if (pingSession) pingSession.cancelled = true;

  const session = { id, cancelled: false };
  pingSession = session;
  pushState();

  (async () => {
    for (let seq = 1; seq <= PING_SESSION_MAX && !session.cancelled; seq += 1) {
      const result = await net.pingOnce(device.ip);
      if (session.cancelled) break;
      if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('ping:sample', { id, seq, ok: result.ok, ms: result.ms });
      }
      // One a second, so the graph reads as a timeline rather than a burst.
      const gap = Math.max(0, 1000 - (result.ok ? result.ms : 0));
      await new Promise((r) => setTimeout(r, gap));
    }
    if (pingSession === session) {
      pingSession = null;
      pushState();
    }
  })();

  return buildState();
});

ipcMain.handle('ping:stop', () => {
  if (pingSession) pingSession.cancelled = true;
  pingSession = null;
  pushState();
  return buildState();
});

ipcMain.handle('device:forget', (_e, { id }) => {
  store.forget(id);
  pushState();
  return buildState();
});

ipcMain.handle('settings:update', (_e, patch) => {
  store.updateSettings(patch || {});
  rescheduleAutoScan();
  pushState();
  return buildState();
});

ipcMain.handle('oui:download', async () => {
  try {
    const result = await oui.download(ouiUserPath());
    // Backfill vendors for devices we already know about.
    for (const device of store.list()) {
      const vendor = oui.lookup(device.mac);
      if (vendor) device.vendor = vendor;
    }
    store.saveDevices();
    pushState();
    return { ok: true, entries: result.entries };
  } catch (err) {
    return { ok: false, error: err.message };
  }
});

ipcMain.handle('app:openDataFolder', () => {
  shell.openPath(app.getPath('userData'));
});
